// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-rr1oL9KoBgYLoNs7AxmWmwWsqgCDRy8',
    appId: '1:37784988212:web:32649fd4c8415d2c32b861',
    messagingSenderId: '37784988212',
    projectId: 'solotrip-4fc3c',
    authDomain: 'solotrip-4fc3c.firebaseapp.com',
    storageBucket: 'solotrip-4fc3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdrlvt6l4eZk7qK_LBITePEARtA8k69ws',
    appId: '1:37784988212:android:f72273c86c20fc0532b861',
    messagingSenderId: '37784988212',
    projectId: 'solotrip-4fc3c',
    storageBucket: 'solotrip-4fc3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_kAQmCENNULWVNgnkMGhnXNkihHCU-cA',
    appId: '1:37784988212:ios:eeb932b3070f6ef332b861',
    messagingSenderId: '37784988212',
    projectId: 'solotrip-4fc3c',
    storageBucket: 'solotrip-4fc3c.appspot.com',
    iosBundleId: 'com.solosavour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_kAQmCENNULWVNgnkMGhnXNkihHCU-cA',
    appId: '1:37784988212:ios:cdaaf4f14687fda132b861',
    messagingSenderId: '37784988212',
    projectId: 'solotrip-4fc3c',
    storageBucket: 'solotrip-4fc3c.appspot.com',
    iosBundleId: 'com.solosavour.RunnerTests',
  );
}
